Added missing break statements to swtich statement
Clients are getting kicked with the following error due to the fall through from the `SERVER` to the `CLIENT` due to the missing break statement:

```
[08:20:38] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel Numina
java.lang.NoSuchMethodError: net.machinemuse.numina.network.MusePacketHandler.getClientPlayer()Lnet/minecraft/entity/player/EntityPlayer;
```